version: '3.9'

services:
  app:
    image: ghcr.io/devisitem/mf-content-api:latest
    ports:
      - "9090:9090"
    environment:
      - FORCE_UPDATE=$(date +%s)
    networks:
      - mf_network

networks:
  mf_network:
    external: true