server:
  port: 9090

project:
  name: mf-content-api
  version: 0.0.1-SNAPSHOT

---
spring:
  jpa:
    open-in-view: false #요청이 끝날때까지 오픈된 세션을 유지하지 않는다.
    properties:
      hibernate.hbm2ddl.auto: create-drop #create-drop : 시작할때 테이블을 삭제 후 생성하고 종료할때 테이블을 삭제한다.
      hibernate:
        show_sql: true
        format_sql: true
  config:
    activate:
      on-profile: local

datasource:
  mission:
    # 도커파일로 실행시
    #    url: jdbc:mysql://mission-db:3306/mf_dev?cacheCallableStmts=true&serverTimezone=Asia/Seoul&useServerPrepStmts=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://localhost:3306/mf_dev?cacheCallableStmts=true&serverTimezone=Asia/Seoul&useServerPrepStmts=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: devis
    driver-class-name: com.mysql.cj.jdbc.Driver
    pull-name: mission
    auto-commit: false

logging:
  level:
#    org.hibernate.SQL: WARN
    com.cofixer.mf.mfcontentapi: DEBUG
  config: classpath:logback-${spring.profiles.active}.xml

springdoc:
  swagger-ui:
    enabled: false
  default-produces-media-type: application/json
---

spring:
  config:
    activate:
      on-profile: doc
  jpa:
    open-in-view: false #요청이 끝날때까지 오픈된 세션을 유지하지 않는다.
    properties:
      hibernate:
        show_sql: true
        format_sql: true

datasource:
  mission:
    # 도커파일로 실행시
    #    url: jdbc:mysql://mission-db:3306/mf_dev?cacheCallableStmts=true&serverTimezone=Asia/Seoul&useServerPrepStmts=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    pull-name: mission
    auto-commit: false

logging:
  level:
    #    org.hibernate.SQL: WARN
    com.cofixer.mf.mfcontentapi: DEBUG

springdoc:
  swagger-ui:
    enabled: false
  default-produces-media-type: application/json